### ISSUE TITLE
1.4.1-BACKEND INFRAESTRUCTURA-Creacion de Microservicio Admin Server

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre#8]
Se requiere desarrollar el MCS De admin server, este servira para poder controlar en tiempo real el estado de todos los MCS con metricas, configuraciones, y variables  que se hayan implemetado en la configuracion de DOCKER.
Este MCS heredara las configuraciones y dependencias del POM padre (Infraestructura) y ademas debera inyectar las siguientes dependencias:

                 <dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-server</artifactId>
			<version>${spring-boot-admin.version}</version>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-client</artifactId>
			<version>${spring-boot-admin.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>4.0.1</version>
			<scope>compile</scope>

**Comment by patiky** [comment]
iniciando desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Renzo-Espinola** [comment]
se revisa que los microservicios esten siendo reflejados, tambien sus configuraciones individuales en el admin server. Es correcto el funcionamiento

**Comment by Renzo-Espinola** [comment]
![Image](https://github.com/CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre/assets/70241433/96a45bbf-e64d-4348-897d-4898ffb66181)

**Comment by Renzo-Espinola** [comment]
![Image](https://github.com/CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre/assets/70241433/abf74076-5afa-433f-ac19-3262712d2399)
