### ISSUE TITLE
1.4.3-BACKEND INFRAESTRUCTURA-Creacion de Microservicio Config Server

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre#9]
Se requiere crear el MCS de configuracion, este servira para administrar mediante un repositorio externo los perfiles de configuracion, esto nos permitira poder cambiar entre los perfiles production y development  a los MCS mediante el DOCKER-COMPOSE.

Perfil Development: Este perfil nos levantara una base de datos de TEST la cual esta alojada en memoria para realizar pruebas.
se debe crear con el siguiente nombre y contenido:

nombre:  config-client-development.properties

contenido:

user.role=Developer
user.alias=patitaspetshop
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:product
spring.datasource.username=sa
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.h2.Driver

Perfil Production: Este perfil nos levantara una base de datos  PostgreSQL la cual se almacenara en un volumen de docker.
se debe crear con el siguiente nombre y contenido:

nombre:  config-client-production.properties

contenido:

user.role=sysadmin
user.alias=patitaspetshop
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/springboot?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

Depedencias: debera heredar del POM padre infraestructura, y ademas inyectar las siguientes dependencias:

                <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>4.0.1</version>
			<scope>compile</scope>

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se valida que las configuraciones establecidas en el repositorio de github, estan siendo obtenidas correctamente.

**Comment by Renzo-Espinola** [comment]
![Image](https://github.com/CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre/assets/70241433/30251148-92de-4342-8445-7528e4a541ae)

**Comment by Renzo-Espinola** [comment]
![Image](https://github.com/CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre/assets/70241433/d162229d-40d1-4cf4-91ec-55f52c943c3e)

**Comment by Renzo-Espinola** [comment]
![Image](https://github.com/CodeSystem2022/ChacoDevsTeam_ProyectoIntegradorCuartoSemestre/assets/70241433/3c109488-4ae3-417a-8f0b-eb9079183dcc)
